### ISSUE TITLE
Version 2.11.0 causing error in require.min.js

### ISSUE THREAD

**Issue by Avvernio** [magesuite/magepack#162] opened 2022-10-25 12:17 UTC
Downgrading to version 2.10.1 resolves the issue.

In the attached (unminified) file line 81 the error: Cannot read properties of undefined (reading 'noConflict')

Magento 2.4.5 @php 8.1

[require.min.txt](https://github.com/magesuite/magepack/files/9860130/require.min.txt)

**Comment by krzksz** [comment] 2022-10-25 13:17
Closing as a duplicate of https://github.com/magesuite/magepack/issues/161

**Closed by krzksz** 2022-10-25 13:17 UTC
